# Generated by Django 4.2.7 on 2025-07-15 02:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Em andamento', 'Em andamento'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('frete', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('endereco_cep', models.CharField(max_length=10)),
                ('endereco_cidade', models.CharField(max_length=100)),
                ('endereco_uf', models.CharField(max_length=2)),
                ('endereco_rua', models.CharField(max_length=255)),
                ('endereco_numero', models.CharField(max_length=20)),
                ('endereco_complemento', models.CharField(blank=True, max_length=100)),
                ('metodo_envio', models.CharField(choices=[('Correios - PAC', 'Correios - PAC'), ('Correios - SEDEX', 'Correios - SEDEX'), ('Transportadora', 'Transportadora'), ('Retirada no local', 'Retirada no local')], default='Correios - PAC', max_length=50)),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedidos',
                'ordering': ['-data_pedido'],
            },
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedido_itens', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
                'db_table': 'pedido_itens',
                'indexes': [models.Index(fields=['pedido'], name='pedido_iten_pedido__97ee42_idx'), models.Index(fields=['produto'], name='pedido_iten_produto_324fb4_idx')],
                'unique_together': {('pedido', 'produto')},
            },
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['numero'], name='pedidos_numero_107754_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['cliente', 'status'], name='pedidos_cliente_e761ce_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['data_pedido', 'status'], name='pedidos_data_pe_28ce8e_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['total'], name='pedidos_total_a37edd_idx'),
        ),
    ]
